/*
 * ============LICENSE_START=======================================================
 * feature-server-pool
 * ================================================================================
 * Copyright (C) 2020 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */
package org.onap.policy.drools.serverpool.test;

import org.onap.policy.drools.serverpool.AdapterImpl;
import org.onap.policy.drools.serverpooltest.Adapter;
import org.onap.policy.drools.serverpooltest.TestDroolsObject;

rule "Initialization"
    when
    then
    {
      System.out.println("Initialization rule running");
    }
end

rule "Receive 'TestDroolsObject'"
    when
        $object : TestDroolsObject()
    then
    {
      Adapter adapter = AdapterImpl.getAdapter();
      String key = $object.getKey();
      System.out.println(adapter.toString()
                         + ": Received TestDroolsObject - key=" + key);
      adapter.notificationQueue().add(key);
      if (!key.contains("SAVE"))
        {
          // 'SAVE' keyword identifies messages that shouldn't be retracted
          retract($object);
        }
    }
end

