/*
 * ============LICENSE_START=======================================================
 * policy-core
 * ================================================================================
 * Copyright (C) 2018 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */
 package org.onap.policy.drools.core.test;

rule "Initialization"
	when
	then
	{
	  System.out.println("Initialization rule running");
	}
end

rule "Add elements of an int array"
	when
		$object : Object()
	then
	{
	  if ($object instanceof int[])
		{
		  int[] array = (int[])($object);

		  System.out.println("Received array of length " + array.length);
		  int sum = 0;
		  for (int i = 1 ; i < array.length ; i += 1)
			{
			  sum += array[i];
			}
		  array[0] = sum;
		  retract($object);
		}
	}
end
