CREATE TABLE SESSIONINFO (ID BIGINT NOT NULL, LASTMODIFICATIONDATE TIMESTAMP, RULESBYTEARRAY LONGVARBINARY, STARTDATE TIMESTAMP, OPTLOCK INTEGER, PRIMARY KEY (ID))
CREATE TABLE WORKITEMINFO (WORKITEMID BIGINT NOT NULL, CREATIONDATE TIMESTAMP, NAME VARCHAR, PROCESSINSTANCEID BIGINT, STATE BIGINT, OPTLOCK INTEGER, WORKITEMBYTEARRAY LONGVARBINARY, PRIMARY KEY (WORKITEMID))
CREATE TABLE IntegrityAuditEntity (id BIGINT NOT NULL, createdDate TIMESTAMP, designated BOOLEAN, jdbcDriver VARCHAR NOT NULL, jdbcPassword VARCHAR NOT NULL, jdbcUrl VARCHAR NOT NULL, jdbcUser VARCHAR NOT NULL, lastUpdated TIMESTAMP, nodeType VARCHAR, persistenceUnit VARCHAR NOT NULL, resourceName VARCHAR NOT NULL UNIQUE, site VARCHAR, PRIMARY KEY (id))
CREATE SEQUENCE SESSIONINFO_ID_SEQ INCREMENT BY 50 START WITH 50
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
CREATE SEQUENCE WORKITEMINFO_ID_SEQ INCREMENT BY 50 START WITH 50
