/*-
 * ============LICENSE_START=======================================================
 * feature-test-transaction
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */
package org.onap.policy.drools.rules;

import java.util.EventObject;

declare ForwardProgress
	counter : Long
end

rule "TT.SETUP"
when
then
	ForwardProgress fp = new ForwardProgress();
	fp.setCounter(0L);
	insert(fp);
end

rule "TT"
when 
	$fp : ForwardProgress()
	$tt : EventObject(source == "43868e59-d1f3-43c2-bd6f-86f89a61eea5")
then
	$fp.setCounter($fp.getCounter() + 1);
	retract($tt);
end

query "TT.FPC"
	ForwardProgress(counter >= 0, $ttc : counter)
end
