package org.onap.policy.drools.core.test;

rule "Initialization"
	when
	then
	{
	  System.out.println("Initialization rule running");
	}
end

rule "Multiply elements of an int array"
	when
		$object : Object()
	then
	{
	  if ($object instanceof int[])
		{
		  int[] array = (int[])($object);

		  System.out.println("Received array of length " + array.length);
		  int product = 1;
		  for (int i = 1 ; i < array.length ; i += 1)
			{
			  product *= array[i];
			}
		  array[0] = product;
		}
	}
end
