#!/usr/bin/env ash

# ============LICENSE_START=======================================================
# feature-controller-logging
# ================================================================================
# Copyright (C) 2019 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

configDir=${POLICY_HOME}/config
for includedConfig in $(ls "${configDir}" | grep "logback-include-.*.xml"); do
    include="\t\<include optional\=\"true\" resource\=\"${includedConfig}\"/\>"
    for mainConfig in ${configDir}/logback.xml ${configDir}/logback-eelf.xml; do
        if [ -e "${mainConfig}" ]; then
            sed -i --follow-symlinks "/\<configuration.*\> /a\ ${include}" "${mainConfig}"
        fi
    done
done
