/*
 * ============LICENSE_START=======================================================
 * ONAP
 * ================================================================================
 * Copyright (C) 2019 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

package rules;

import org.onap.policy.drools.controller.internal.MavenDroolsController3Test;

declare Version
    version : String
end

rule "SETUP.1"
when
then
    Version v1 = new Version();
    v1.setVersion("1");
    insert(v1);

    MavenDroolsController3Test.running1a.countDown();
end

rule "VERSION.12"
when
    $v12 : Version( version == "12")
then
    retract($v12);

    MavenDroolsController3Test.running1b.countDown();
end