/*-
 * ============LICENSE_START=======================================================
 * ONAP
 * ================================================================================
 * Copyright (C) 2019 AT&T Intellectual Property. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

package rules;

import org.onap.policy.drools.controller.internal.MavenDroolsControllerUpgradesTest;

declare Version
    version : String
end

rule "SETUP.2"
when
then
    Version v2 = new Version();
    v2.setVersion("2");
    insert(v2);

    MavenDroolsControllerUpgradesTest.running2a.countDown();
end

rule "VERSION.2"
when
    $v1 : Version( version == "1")
then
    retract($v1);

    Version v12 = new Version();
    v12.setVersion("12");
    insert(v12);

    MavenDroolsControllerUpgradesTest.running2b.countDown();
end
